version: '3.8'

services:
  db:
    image: postgres:17.0-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    restart: always
    networks:
      - kiosco_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    read_only: true
    tmpfs:
      - /tmp
    depends_on:
      db:
        condition: service_healthy
    environment:
      HOST: "0.0.0.0"
      PORT: "3200"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      PGSSLMODE: disable
    ports:
      - "127.0.0.1:3200:3200"
    restart: always
    networks:
      - kiosco_net

volumes:
  postgres_data:
    name: kiosco_postgres_data

networks:
  kiosco_net:
